version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mailScheduller
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BASE_URL=http://backend:5000

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mailScheduller
    ports:
      - "5432:5432"

  redis:
    image: redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # MailHog web interface
      - "1025:1025"  # MailHog SMTP server